on: [pull_request]
name: tests
jobs: 
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout repo content
      with: 
        ref: ${{ github.ref }}
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install networkx lxml
    - name: Convert files
      run: |
        files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{github.event.pull_request.head.sha}})
        for changed_file in $files; do
          if [ "${changed_file: -9}" == "stemma.gv" ] || [ "${changed_file: -12}" == "metadata.txt" ] ; 
            then echo "Converting ${changed_file}."
            python ./transform/transformation.py ${changed_file} ; 
          fi
        done
    - uses: r-lib/actions/setup-r@v1
      id: install-r  
    - name: Install dependencies
      run: install.packages(c("testthat", "stringr", "xml2")) #"sna" , "igraph", "DiagrammeR"))
      shell: Rscript {0}
    # - run: Rscript -e "getwd()"
    - run: Rscript tests/testthat.R
    #- uses: actions/checkout@master
    #- name: Test
    #  uses: skx/github-action-tester@master



