name: Transform

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/get-diff-action@v5
      - name: checkout repo content
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx lxml
      - name: Convert files
        run: |
          echo "Git diff ${{ env.GIT_DIFF }}"
          for changed_file in ${{ env.GIT_DIFF }}; do
            if [ "${changed_file: -9}" == "stemma.gv" ] || [ "${changed_file: -12}" == "metadata.txt" ] ; 
              then echo "Converting ${changed_file}."
              python ./transform/transformation.py ${changed_file} ; 
            fi
          done
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Auto-Generation TEI
