name: Transform

on: 
  push:
      branches-ignore:
        - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx lxml
      - name: Set env
        run: echo "mastersha=$(git log -n 1 master --pretty=format:"%H")" >> $GITHUB_ENV
      - name: Convert files
        run: |
          files=$(git diff --name-only ${{ github.sha }} ${{env.mastersha}})
          for changed_file in $files; do
            if [ "${changed_file: -9}" == "stemma.gv" ] || [ "${changed_file: -12}" == "metadata.txt" ] ; 
              then echo "Converting ${changed_file}."
              python ./transform/transformation.py ${changed_file} ; 
            fi
          done
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Auto-Generation TEI
