name: Transform

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx
      - name: Find changed files
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
      - name: Run transformation
        run: |
          python ./generateTeiGraphml.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-Generation TEI